--RobotDynamicState and Robot

INSERT INTO ROBOT_DYNAMIC_STATE(SERIAL_NUMBER, BATTERY_CAPACITY, ROBOT_STATE) VALUES ('ABC1', 100, 'IDLE')
INSERT INTO ROBOT (SERIAL_NUMBER, ROBOT_MODEL, WEIGHT_LIMIT) VALUES('ABC1', 'LIGHTWEIGHT' , 250)

INSERT INTO ROBOT_DYNAMIC_STATE(SERIAL_NUMBER, BATTERY_CAPACITY, ROBOT_STATE) VALUES ('ABC12', 85, 'LOADING')
INSERT INTO ROBOT (SERIAL_NUMBER, ROBOT_MODEL, WEIGHT_LIMIT) VALUES('ABC12', 'LIGHTWEIGHT' , 300)

INSERT INTO ROBOT_DYNAMIC_STATE(SERIAL_NUMBER, BATTERY_CAPACITY, ROBOT_STATE) VALUES ('ABC123', 70, 'RETURNING')
INSERT INTO ROBOT (SERIAL_NUMBER, ROBOT_MODEL, WEIGHT_LIMIT) VALUES('ABC123', 'MIDDLEWEIGHT' , 370)

INSERT INTO ROBOT_DYNAMIC_STATE(SERIAL_NUMBER, BATTERY_CAPACITY, ROBOT_STATE) VALUES ('ABC1234', 23, 'IDLE')
INSERT INTO ROBOT (SERIAL_NUMBER, ROBOT_MODEL, WEIGHT_LIMIT) VALUES('ABC1234', 'CRUISERWEIGHT' , 420)

INSERT INTO ROBOT_DYNAMIC_STATE(SERIAL_NUMBER, BATTERY_CAPACITY, ROBOT_STATE) VALUES ('ABC12345', 42, 'DELIVERING')
INSERT INTO ROBOT (SERIAL_NUMBER, ROBOT_MODEL, WEIGHT_LIMIT) VALUES('ABC12345', 'HEAVYWEIGHT' , 500)

--Medication
INSERT INTO MEDICATION (NAME, CODE, WEIGHT, IMAGE_URL) VALUES('PANADOL', 'ABC1' , 50, 'static/images/panadol')
INSERT INTO MEDICATION (NAME, CODE, WEIGHT, IMAGE_URL) VALUES('ADOL', 'ABC12' , 43, 'static/images/adol')
INSERT INTO MEDICATION (NAME, CODE, WEIGHT, IMAGE_URL) VALUES('SOLOFRESH', 'ABC123' , 27, 'static/images/solofresh')
INSERT INTO MEDICATION (NAME, CODE, WEIGHT, IMAGE_URL) VALUES('SYRINGE', 'ABC1234' , 70, 'static/image/syringe')
INSERT INTO MEDICATION (NAME, CODE, WEIGHT, IMAGE_URL) VALUES('BRUFEN', 'ABC12345' , 65, 'static/image/brufen')
